/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrame;

import javax.swing.JOptionPane;

import lite.util;
import mooer.ChangeImg;
import mooer.Golbal;

/**
 * @author Evistix
 */
public class Card_Map_6 extends javax.swing.JFrame {
    int CardNum = 0;

    void updateIcon() {
        if( Golbal.Cards_isHave[51] ) ChangeImg.changeImg( jLabel1, 51 );
        else new ChangeImg().changeImgBlack( jLabel1, 51 );
        if( Golbal.Cards_isHave[52] ) ChangeImg.changeImg( jLabel2, 52 );
        else new ChangeImg().changeImgBlack( jLabel2, 52 );
        if( Golbal.Cards_isHave[53] ) ChangeImg.changeImg( jLabel3, 53 );
        else new ChangeImg().changeImgBlack( jLabel3, 53 );
        if( Golbal.Cards_isHave[54] ) ChangeImg.changeImg( jLabel4, 54 );
        else new ChangeImg().changeImgBlack( jLabel4, 54 );
        if( Golbal.Cards_isHave[55] ) ChangeImg.changeImg( jLabel5, 55 );
        else new ChangeImg().changeImgBlack( jLabel5, 55 );
        if( Golbal.Cards_isHave[56] ) ChangeImg.changeImg( jLabel6, 56 );
        else new ChangeImg().changeImgBlack( jLabel6, 56 );
        if( Golbal.Cards_isHave[57] ) ChangeImg.changeImg( jLabel7, 57 );
        else new ChangeImg().changeImgBlack( jLabel7, 57 );
        if( Golbal.Cards_isHave[58] ) ChangeImg.changeImg( jLabel8, 58 );
        else new ChangeImg().changeImgBlack( jLabel8, 58 );
        if( Golbal.Cards_isHave[59] ) ChangeImg.changeImg( jLabel9, 59 );
        else new ChangeImg().changeImgBlack( jLabel9, 59 );
        if( Golbal.Cards_isHave[60] ) ChangeImg.changeImg( jLabel10, 60 );
        else new ChangeImg().changeImgBlack( jLabel10, 60 );
        等级.setText( "等级：" + Golbal.level );
        点券.setText( "点券：" + Golbal.UserBalance );
        呢称.setText( "昵称：" + Golbal.Account );
        Golbal.CalCardsNum();
        拥有卡牌.setText( "当前拥有卡牌数：" + Golbal.CardNum );
    }

    /**
     * Creates new form Card_Map
     */
    public Card_Map_6() {
        initComponents();
        updateIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        购买选择 = new javax.swing.ButtonGroup();
        backGround = new javax.swing.JPanel();
        头像 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        水1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        水2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        水3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        水4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        水5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        水6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        水7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        水8 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        水9 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        水10 = new javax.swing.JRadioButton();
        拥有卡牌 = new javax.swing.JLabel();
        返回 = new javax.swing.JButton();
        购买 = new javax.swing.JButton();
        上一页 = new javax.swing.JButton();
        等级 = new javax.swing.JLabel();
        点券 = new javax.swing.JLabel();
        呢称 = new javax.swing.JLabel();
        Front = new javax.swing.JPanel();
        背景 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("商城");

        backGround.setOpaque(false);
        backGround.setPreferredSize(new java.awt.Dimension(1000, 700));

        头像.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        头像.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/i1.gif"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水1);
        水1.setText("火—11");
        水1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水2);
        水2.setText("火—12");
        水2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水3);
        水3.setText("火—13");
        水3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水3ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水4);
        水4.setText("火—14");
        水4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水4ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水5);
        水5.setText("火—15");
        水5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水5ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水6);
        水6.setText("火—16");
        水6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水6ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水7);
        水7.setText("火—17");
        水7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水7ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水8);
        水8.setText("火—18");
        水8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水8ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水9);
        水9.setText("火—19");
        水9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水9ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_small/1.jpg"))); // NOI18N

        购买选择.add(水10);
        水10.setText("火—20");
        水10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                水10ActionPerformed(evt);
            }
        });

        拥有卡牌.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        拥有卡牌.setText("拥有卡牌数X/X");

        返回.setText("返回");
        返回.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                返回ActionPerformed(evt);
            }
        });

        购买.setText("购买");
        购买.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                购买ActionPerformed(evt);
            }
        });

        上一页.setText("上一页");
        上一页.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                上一页ActionPerformed(evt);
            }
        });

        等级.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        等级.setText("等级");

        点券.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        点券.setText("点券");

        呢称.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        呢称.setText("呢称");

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(水6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(水7))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(水8))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(水9))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(水10))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(头像, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(等级, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(呢称, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(拥有卡牌, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(购买, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(返回, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(点券, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(上一页, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(水1))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(水2)
                        .addGap(101, 101, 101)))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(水3))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(水4))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(水5)
                        .addGap(103, 103, 103))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(头像, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(拥有卡牌, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(购买, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(返回, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(呢称)
                        .addGap(18, 18, 18)
                        .addComponent(等级)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(点券)
                        .addGap(27, 27, 27)))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水1))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水2))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水3))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水4))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水5)))
                .addGap(28, 28, 28)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水9))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水10))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(水7)
                            .addComponent(水6)))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(水8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(上一页, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Front.setOpaque(false);

        背景.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backGround/b2.png"))); // NOI18N

        javax.swing.GroupLayout FrontLayout = new javax.swing.GroupLayout(Front);
        Front.setLayout(FrontLayout);
        FrontLayout.setHorizontalGroup(
            FrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(FrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FrontLayout.createSequentialGroup()
                    .addComponent(背景)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FrontLayout.setVerticalGroup(
            FrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(FrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(背景, javax.swing.GroupLayout.PREFERRED_SIZE, 687, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Front, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Front, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 返回ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_返回ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Main_UI().setVisible( true );
    }//GEN-LAST:event_返回ActionPerformed

    private void 水1ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水1ActionPerformed
        CardNum = 51;
        // TODO add your handling code here:
    }//GEN-LAST:event_水1ActionPerformed

    private void 水2ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水2ActionPerformed
        CardNum = 52;
        // TODO add your handling code here:
    }//GEN-LAST:event_水2ActionPerformed

    private void 水3ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水3ActionPerformed
        CardNum = 53;
        // TODO add your handling code here:
    }//GEN-LAST:event_水3ActionPerformed

    private void 水4ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水4ActionPerformed
        CardNum = 54;
        // TODO add your handling code here:
    }//GEN-LAST:event_水4ActionPerformed

    private void 水5ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水5ActionPerformed
        CardNum = 55;
        // TODO add your handling code here:
    }//GEN-LAST:event_水5ActionPerformed

    private void 水6ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水6ActionPerformed
        CardNum = 56;
        // TODO add your handling code here:
    }//GEN-LAST:event_水6ActionPerformed

    private void 水7ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水7ActionPerformed
        CardNum = 57;
        // TODO add your handling code here:
    }//GEN-LAST:event_水7ActionPerformed

    private void 水8ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水8ActionPerformed
        CardNum = 58;
        // TODO add your handling code here:
    }//GEN-LAST:event_水8ActionPerformed

    private void 水9ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水9ActionPerformed
        CardNum = 59;
        // TODO add your handling code here:
    }//GEN-LAST:event_水9ActionPerformed

    private void 水10ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_水10ActionPerformed
        CardNum = 60;
        // TODO add your handling code here:
    }//GEN-LAST:event_水10ActionPerformed

    private void 上一页ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_上一页ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Card_Map_5().setVisible( true );
    }//GEN-LAST:event_上一页ActionPerformed

    private void 购买ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_购买ActionPerformed
        int price = 2000;//价格
        if( CardNum == 0 ){
            JOptionPane.showMessageDialog( null, "未选择卡牌", "提示信息", JOptionPane.INFORMATION_MESSAGE );
            return;
        }
        if( JOptionPane.showConfirmDialog( null, "是否用2000点劵购买？", "确认", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE ) == JOptionPane.YES_OPTION ){
            if( Golbal.UserBalance >= 2000 ){

                Golbal.UserBalance -= 2000;
                Golbal.Cards_isHave[CardNum] = true;
                int num = CardNum;
                CardNum = 0;
                updateIcon();
                util.Gacha( Golbal.UserUid, 2000 );
                util.getCard( Golbal.UserUid, Golbal.cardsList[num].type + Golbal.cardsList[num].var );
                util.setCardQuantity( Golbal.UserUid );
                Golbal.CardNum = util.getCardQuantity( Golbal.UserUid );
            }
            else{
                JOptionPane.showMessageDialog( null, "余额不足", "提示信息", JOptionPane.INFORMATION_MESSAGE );
                return;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_购买ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ){
                if( "Nimbus".equals( info.getName() ) ){
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }catch( ClassNotFoundException ex ){
            java.util.logging.Logger.getLogger( Card_Map_6.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( InstantiationException ex ){
            java.util.logging.Logger.getLogger( Card_Map_6.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( IllegalAccessException ex ){
            java.util.logging.Logger.getLogger( Card_Map_6.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( javax.swing.UnsupportedLookAndFeelException ex ){
            java.util.logging.Logger.getLogger( Card_Map_6.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Card_Map_6().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Front;
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton 上一页;
    private javax.swing.JLabel 呢称;
    private javax.swing.JLabel 头像;
    private javax.swing.JLabel 拥有卡牌;
    private javax.swing.JRadioButton 水1;
    private javax.swing.JRadioButton 水10;
    private javax.swing.JRadioButton 水2;
    private javax.swing.JRadioButton 水3;
    private javax.swing.JRadioButton 水4;
    private javax.swing.JRadioButton 水5;
    private javax.swing.JRadioButton 水6;
    private javax.swing.JRadioButton 水7;
    private javax.swing.JRadioButton 水8;
    private javax.swing.JRadioButton 水9;
    private javax.swing.JLabel 点券;
    private javax.swing.JLabel 等级;
    private javax.swing.JLabel 背景;
    private javax.swing.JButton 购买;
    private javax.swing.ButtonGroup 购买选择;
    private javax.swing.JButton 返回;
    // End of variables declaration//GEN-END:variables
}
