/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrame;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 * @author Evistix
 */
public class Card_Map__定制代码demo extends javax.swing.JFrame {

    /**
     * Creates new form Card_Map
     */
    public Card_Map__定制代码demo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel() {
            protected void paintComponent( Graphics g ) {
                super.paintComponent( g );
                ImageIcon img = new ImageIcon( getClass().getClassLoader().getResource( "backGround/b2.png" ) );
                g.drawImage( img.getImage(), 0, 0, getWidth(), getHeight(), null );
            }
        }
        ;
        信息 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        水1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        水2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        水3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        水4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        水5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        水6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        水7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        水8 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        水9 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        水10 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

        backGround.setOpaque( false );
        backGround.setPreferredSize( new java.awt.Dimension( 1000, 700 ) );

        信息.setFont( new java.awt.Font( "宋体", 0, 18 ) ); // NOI18N
        信息.setText( "这里到时候放角色信息，右边放金币" );

        jLabel1.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水1.setText( "水—1" );

        jLabel2.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水2.setText( "水—1" );

        jLabel3.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水3.setText( "水—1" );

        jLabel4.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水4.setText( "水—1" );

        jLabel5.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水5.setText( "水—1" );

        jLabel6.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水6.setText( "水—1" );

        jLabel7.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水7.setText( "水—1" );

        jLabel8.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水8.setText( "水—1" );

        jLabel9.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水9.setText( "水—1" );

        jLabel10.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/Img_small/1.jpg" ) ) ); // NOI18N

        水10.setText( "水—1" );

        jLabel12.setFont( new java.awt.Font( "宋体", 1, 18 ) ); // NOI18N
        jLabel12.setText( "拥有卡牌数X/X" );

        jButton1.setText( "返回" );

        jButton2.setText( "购买" );

        jButton3.setText( "上一页" );

        jButton4.setText( "下一页" );

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout( backGround );
        backGround.setLayout( backGroundLayout );
        backGroundLayout.setHorizontalGroup(
                backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( backGroundLayout.createSequentialGroup()
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 68, 68, 68 )
                                                .addComponent( 水1 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 34, 34, 34 )
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addComponent( jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                        .addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) ) ) )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 44, 44, 44 )
                                                .addComponent( jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 45, 45, 45 ) )
                                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                .addComponent( 水2 )
                                                .addGap( 101, 101, 101 ) ) )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 34, 34, 34 )
                                                .addComponent( 水3 ) )
                                        .addComponent( jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addGap( 38, 38, 38 )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 34, 34, 34 )
                                                .addComponent( 水4 ) )
                                        .addComponent( jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                                .addComponent( 水5 )
                                                .addGap( 103, 103, 103 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 43, 43, 43 )
                                                .addComponent( jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addContainerGap( 44, Short.MAX_VALUE ) ) ) )
                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                                .addGap( 81, 81, 81 )
                                .addComponent( 水6 )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                .addComponent( 水7 ) )
                                                        .addComponent( jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                .addGap( 44, 44, 44 )
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                .addComponent( 水8 ) )
                                                        .addComponent( jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 389, 389, 389 )
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                .addComponent( 水9 ) )
                                                        .addComponent( jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                .addGap( 38, 38, 38 )
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                .addComponent( 水10 ) )
                                                        .addComponent( jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE ) ) ) )
                                .addGap( 44, 44, 44 ) )
                        .addGroup( backGroundLayout.createSequentialGroup()
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent( 信息, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 18, 18, 18 )
                                                .addComponent( jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 73, 73, 73 )
                                                .addComponent( jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 62, 62, 62 )
                                                .addComponent( jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGap( 191, 191, 191 )
                                                .addComponent( jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE ) ) )
                                .addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                        .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                                        .addContainerGap( 735, Short.MAX_VALUE )
                                        .addComponent( jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addGap( 92, 92, 92 ) ) )
                                           );
        backGroundLayout.setVerticalGroup(
                backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( backGroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( 信息, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addGap( 18, 18, 18 )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水1 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水2 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水3 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水4 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水5 ) ) )
                                .addGap( 28, 28, 28 )
                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水9 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水10 ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false )
                                                        .addComponent( jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE )
                                                        .addComponent( jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                                .addGap( 6, 6, 6 )
                                                .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                                        .addComponent( 水7 )
                                                        .addComponent( 水6 ) ) )
                                        .addGroup( backGroundLayout.createSequentialGroup()
                                                .addComponent( jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 6, 6, 6 )
                                                .addComponent( 水8 ) ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE )
                                .addComponent( jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addContainerGap() )
                        .addGroup( backGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                                        .addContainerGap( 642, Short.MAX_VALUE )
                                        .addComponent( jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addGap( 13, 13, 13 ) ) )
                                         );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( layout.createSequentialGroup()
                                .addComponent( backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 0, 2, Short.MAX_VALUE ) )
                                 );
        layout.setVerticalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addComponent( backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                               );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ){
                if( "Nimbus".equals( info.getName() ) ){
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }catch( ClassNotFoundException ex ){
            java.util.logging.Logger.getLogger( Card_Map__定制代码demo.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( InstantiationException ex ){
            java.util.logging.Logger.getLogger( Card_Map__定制代码demo.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( IllegalAccessException ex ){
            java.util.logging.Logger.getLogger( Card_Map__定制代码demo.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( javax.swing.UnsupportedLookAndFeelException ex ){
            java.util.logging.Logger.getLogger( Card_Map__定制代码demo.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Card_Map__定制代码demo().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel 信息;
    private javax.swing.JRadioButton 水1;
    private javax.swing.JRadioButton 水10;
    private javax.swing.JRadioButton 水2;
    private javax.swing.JRadioButton 水3;
    private javax.swing.JRadioButton 水4;
    private javax.swing.JRadioButton 水5;
    private javax.swing.JRadioButton 水6;
    private javax.swing.JRadioButton 水7;
    private javax.swing.JRadioButton 水8;
    private javax.swing.JRadioButton 水9;
    // End of variables declaration//GEN-END:variables
}
