/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrame;

import javax.swing.JOptionPane;

import lite.util;
import mooer.*;

/**
 * @author Evistix
 */
public class Gacha_5 extends javax.swing.JFrame {
    void updateIcon() {
        等级.setText( "等级：" + Golbal.level );
        点券.setText( "点券：" + Golbal.UserBalance );
        呢称.setText( "昵称：" + Golbal.Account );
    }

    /**
     * Creates new form Store
     */
    public Gacha_5() {
        initComponents();
        updateIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Up = new javax.swing.JPanel();
        购买 = new javax.swing.JButton();
        返回 = new javax.swing.JButton();
        充值 = new javax.swing.JButton();
        点券400 = new javax.swing.JLabel();
        头像 = new javax.swing.JLabel();
        点券 = new javax.swing.JLabel();
        呢称 = new javax.swing.JLabel();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        Card4 = new javax.swing.JLabel();
        Card5 = new javax.swing.JLabel();
        卡牌属性1 = new javax.swing.JLabel();
        卡牌属性2 = new javax.swing.JLabel();
        卡牌属性3 = new javax.swing.JLabel();
        卡牌属性4 = new javax.swing.JLabel();
        卡牌属性5 = new javax.swing.JLabel();
        等级 = new javax.swing.JLabel();
        BackGround = new javax.swing.JPanel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );
        setTitle( "五连抽" );

        Up.setOpaque( false );
        Up.setLayout( new org.netbeans.lib.awtextra.AbsoluteLayout() );

        购买.setBackground( new java.awt.Color( 153, 153, 255 ) );
        购买.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        购买.setForeground( new java.awt.Color( 255, 102, 153 ) );
        购买.setText( "五连抽" );
        购买.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                购买ActionPerformed( evt );
            }
        } );
        Up.add( 购买, new org.netbeans.lib.awtextra.AbsoluteConstraints( 428, 556, 187, 76 ) );

        返回.setBackground( new java.awt.Color( 153, 153, 255 ) );
        返回.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        返回.setForeground( new java.awt.Color( 0, 51, 204 ) );
        返回.setText( "返回" );
        返回.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                返回ActionPerformed( evt );
            }
        } );
        Up.add( 返回, new org.netbeans.lib.awtextra.AbsoluteConstraints( 642, 652, 187, 76 ) );

        充值.setBackground( new java.awt.Color( 0, 204, 204 ) );
        充值.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        充值.setForeground( new java.awt.Color( 204, 255, 204 ) );
        充值.setText( "充值" );
        充值.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                充值ActionPerformed( evt );
            }
        } );
        Up.add( 充值, new org.netbeans.lib.awtextra.AbsoluteConstraints( 220, 650, 187, 76 ) );

        点券400.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        点券400.setForeground( new java.awt.Color( 255, 102, 102 ) );
        点券400.setText( "400点券" );
        Up.add( 点券400, new org.netbeans.lib.awtextra.AbsoluteConstraints( 472, 650, 105, 33 ) );

        头像.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/i1.gif" ) ) ); // NOI18N
        头像.setToolTipText( "" );
        Up.add( 头像, new org.netbeans.lib.awtextra.AbsoluteConstraints( 37, 31, 100, 100 ) );

        点券.setFont( new java.awt.Font( "宋体", 1, 12 ) ); // NOI18N
        点券.setText( "点券：114514" );
        Up.add( 点券, new org.netbeans.lib.awtextra.AbsoluteConstraints( 170, 90, 116, 38 ) );

        呢称.setFont( new java.awt.Font( "宋体", 1, 14 ) ); // NOI18N
        呢称.setText( "呢称" );
        Up.add( 呢称, new org.netbeans.lib.awtextra.AbsoluteConstraints( 170, 40, -1, -1 ) );

        Card1.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/问号.png" ) ) ); // NOI18N
        Up.add( Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints( 440, 60, -1, -1 ) );

        Card2.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/问号.png" ) ) ); // NOI18N
        Up.add( Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints( 220, 130, -1, -1 ) );

        Card3.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/问号.png" ) ) ); // NOI18N
        Up.add( Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints( 330, 350, -1, -1 ) );

        Card4.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/问号.png" ) ) ); // NOI18N
        Up.add( Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints( 570, 350, -1, -1 ) );

        Card5.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/问号.png" ) ) ); // NOI18N
        Up.add( Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints( 680, 130, -1, -1 ) );

        卡牌属性1.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        卡牌属性1.setForeground( new java.awt.Color( 255, 255, 51 ) );
        Up.add( 卡牌属性1, new org.netbeans.lib.awtextra.AbsoluteConstraints( 470, 20, 90, 40 ) );

        卡牌属性2.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        卡牌属性2.setForeground( new java.awt.Color( 255, 255, 51 ) );
        Up.add( 卡牌属性2, new org.netbeans.lib.awtextra.AbsoluteConstraints( 120, 220, 90, 40 ) );

        卡牌属性3.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        卡牌属性3.setForeground( new java.awt.Color( 255, 255, 51 ) );
        Up.add( 卡牌属性3, new org.netbeans.lib.awtextra.AbsoluteConstraints( 220, 430, 90, 40 ) );

        卡牌属性4.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        卡牌属性4.setForeground( new java.awt.Color( 255, 255, 51 ) );
        Up.add( 卡牌属性4, new org.netbeans.lib.awtextra.AbsoluteConstraints( 740, 430, 90, 40 ) );

        卡牌属性5.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        卡牌属性5.setForeground( new java.awt.Color( 255, 255, 51 ) );
        Up.add( 卡牌属性5, new org.netbeans.lib.awtextra.AbsoluteConstraints( 840, 210, 90, 40 ) );

        等级.setFont( new java.awt.Font( "宋体", 1, 14 ) ); // NOI18N
        等级.setText( "呢称" );
        Up.add( 等级, new org.netbeans.lib.awtextra.AbsoluteConstraints( 170, 70, -1, -1 ) );

        BackGroundLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/backGround/b1.png" ) ) ); // NOI18N
        BackGroundLabel.setOpaque( true );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout( BackGround );
        BackGround.setLayout( BackGroundLayout );
        BackGroundLayout.setHorizontalGroup(
                BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 1022, Short.MAX_VALUE )
                        .addGroup( BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( BackGroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent( BackGroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addContainerGap() ) )
                                           );
        BackGroundLayout.setVerticalGroup(
                BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 760, Short.MAX_VALUE )
                        .addGroup( BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( BackGroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent( BackGroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addContainerGap() ) )
                                         );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 1022, Short.MAX_VALUE )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                 );
        layout.setVerticalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 760, Short.MAX_VALUE )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                               );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 返回ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_返回ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Store_Gacha().setVisible( true );
    }//GEN-LAST:event_返回ActionPerformed

    private void 充值ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_充值ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Recharge().setVisible( true );
    }//GEN-LAST:event_充值ActionPerformed

    private void 购买ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_购买ActionPerformed
        //  JOptionPane.showConfirmDialog(null,"400点券一次，确定进行5连抽吗？","确认",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//JOptionPane.showMessageDialog(null, "已经是最后一条数据！","已经是最后一条数据！",JOptionPane.INFORMATION_MESSAGE);
        //==JOptionPane.YES_OPTION
        if( JOptionPane.showConfirmDialog( null, "400点券一次，确定进行5连抽吗？", "确认", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE ) == JOptionPane.YES_OPTION ){
            if( Golbal.UserBalance >= 400 ){
                int Card[] = new int[5];
                for( int i = 0; i < 5; i++ ){
                    Card[i] = Gacha.result( System.nanoTime() % 0x7f7f7f7f );
                }
                ChangeImg.changeImg( Card1, Card[0] );
                卡牌属性1.setText( Golbal.cardsList[Card[0]].type + Golbal.cardsList[Card[0]].var );
                ChangeImg.changeImg( Card2, Card[1] );
                卡牌属性2.setText( Golbal.cardsList[Card[1]].type + Golbal.cardsList[Card[1]].var );
                ChangeImg.changeImg( Card3, Card[2] );
                卡牌属性3.setText( Golbal.cardsList[Card[2]].type + Golbal.cardsList[Card[2]].var );
                ChangeImg.changeImg( Card4, Card[3] );
                卡牌属性4.setText( Golbal.cardsList[Card[3]].type + Golbal.cardsList[Card[3]].var );
                ChangeImg.changeImg( Card5, Card[4] );
                卡牌属性5.setText( Golbal.cardsList[Card[4]].type + Golbal.cardsList[Card[4]].var );
                util.Gacha( Golbal.UserUid, 400 );
                for( int i = 0; i < 5; i++ ){
                    util.getCard( Golbal.UserUid, Golbal.cardsList[Card[i]].type + Golbal.cardsList[Card[i]].var );
                }
                util.setCardQuantity( Golbal.UserUid );
                Golbal.CardNum = util.getCardQuantity( Golbal.UserUid );
                Golbal.UserBalance = util.getUserBalance( Golbal.UserUid );
                Golbal.Cards_isHave = util.colles( Golbal.UserUid );
                点券.setText( "点券：" + Golbal.UserBalance );
                updateIcon();
                Golbal.CalCardsNum();
            }
            else{
                JOptionPane.showMessageDialog( null, "余额不足！", "", JOptionPane.INFORMATION_MESSAGE );
            }
        }
    }//GEN-LAST:event_购买ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ){
                if( "Nimbus".equals( info.getName() ) ){
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }catch( ClassNotFoundException ex ){
            java.util.logging.Logger.getLogger( Gacha_5.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( InstantiationException ex ){
            java.util.logging.Logger.getLogger( Gacha_5.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( IllegalAccessException ex ){
            java.util.logging.Logger.getLogger( Gacha_5.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( javax.swing.UnsupportedLookAndFeelException ex ){
            java.util.logging.Logger.getLogger( Gacha_5.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Gacha_5().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Card4;
    private javax.swing.JLabel Card5;
    private javax.swing.JPanel Up;
    private javax.swing.JButton 充值;
    private javax.swing.JLabel 卡牌属性1;
    private javax.swing.JLabel 卡牌属性2;
    private javax.swing.JLabel 卡牌属性3;
    private javax.swing.JLabel 卡牌属性4;
    private javax.swing.JLabel 卡牌属性5;
    private javax.swing.JLabel 呢称;
    private javax.swing.JLabel 头像;
    private javax.swing.JLabel 点券;
    private javax.swing.JLabel 点券400;
    private javax.swing.JLabel 等级;
    private javax.swing.JButton 购买;
    private javax.swing.JButton 返回;
    // End of variables declaration//GEN-END:variables
}
