/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrame;

import mooer.Golbal;

/**
 * @author Evistix
 */
public class Store_Gacha extends javax.swing.JFrame {
    void updateIcon() {
        等级.setText( "等级：" + Golbal.level );
        点券.setText( "点券：" + Golbal.UserBalance );
        呢称.setText( "昵称：" + Golbal.Account );
    }

    /**
     * Creates new form Store
     */
    public Store_Gacha() {
        initComponents();
        updateIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Up = new javax.swing.JPanel();
        购买 = new javax.swing.JButton();
        抽卡 = new javax.swing.JButton();
        返回 = new javax.swing.JButton();
        充值 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        头像 = new javax.swing.JLabel();
        呢称 = new javax.swing.JLabel();
        等级 = new javax.swing.JLabel();
        点券 = new javax.swing.JLabel();
        BackGround = new javax.swing.JPanel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

        Up.setOpaque( false );

        购买.setBackground( new java.awt.Color( 153, 153, 255 ) );
        购买.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        购买.setForeground( new java.awt.Color( 255, 102, 153 ) );
        购买.setText( "单抽" );
        购买.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                购买ActionPerformed( evt );
            }
        } );

        抽卡.setBackground( new java.awt.Color( 153, 255, 255 ) );
        抽卡.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        抽卡.setForeground( new java.awt.Color( 0, 204, 102 ) );
        抽卡.setText( "五连抽" );
        抽卡.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                抽卡ActionPerformed( evt );
            }
        } );

        返回.setBackground( new java.awt.Color( 153, 153, 255 ) );
        返回.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        返回.setForeground( new java.awt.Color( 0, 51, 204 ) );
        返回.setText( "返回" );
        返回.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                返回ActionPerformed( evt );
            }
        } );

        充值.setBackground( new java.awt.Color( 0, 204, 204 ) );
        充值.setFont( new java.awt.Font( "宋体", 1, 36 ) ); // NOI18N
        充值.setForeground( new java.awt.Color( 204, 255, 204 ) );
        充值.setText( "充值" );
        充值.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                充值ActionPerformed( evt );
            }
        } );

        jLabel1.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        jLabel1.setForeground( new java.awt.Color( 255, 102, 102 ) );
        jLabel1.setText( "100点券" );

        jLabel2.setFont( new java.awt.Font( "宋体", 1, 24 ) ); // NOI18N
        jLabel2.setForeground( new java.awt.Color( 255, 102, 102 ) );
        jLabel2.setText( "400点券" );

        头像.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/icon/i1.gif" ) ) ); // NOI18N
        头像.setToolTipText( "" );

        呢称.setFont( new java.awt.Font( "宋体", 1, 14 ) ); // NOI18N
        呢称.setText( "呢称" );

        等级.setFont( new java.awt.Font( "宋体", 1, 14 ) ); // NOI18N
        等级.setText( "等级" );

        点券.setFont( new java.awt.Font( "宋体", 1, 14 ) ); // NOI18N
        点券.setText( "点券" );

        javax.swing.GroupLayout UpLayout = new javax.swing.GroupLayout( Up );
        Up.setLayout( UpLayout );
        UpLayout.setHorizontalGroup(
                UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, UpLayout.createSequentialGroup()
                                .addGap( 207, 207, 207 )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addComponent( 充值, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( 购买, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addComponent( 返回, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( 抽卡, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addGap( 195, 195, 195 ) )
                        .addGroup( UpLayout.createSequentialGroup()
                                .addGap( 250, 250, 250 )
                                .addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                .addComponent( jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 225, 225, 225 ) )
                        .addGroup( UpLayout.createSequentialGroup()
                                .addGap( 37, 37, 37 )
                                .addComponent( 头像, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 18, 18, 18 )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addComponent( 呢称, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( 等级, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( 点券, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                   );
        UpLayout.setVerticalGroup(
                UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( UpLayout.createSequentialGroup()
                                .addGap( 31, 31, 31 )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                        .addComponent( 头像, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addGroup( UpLayout.createSequentialGroup()
                                                .addComponent( 呢称, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 20, 20, 20 )
                                                .addComponent( 等级 )
                                                .addGap( 24, 24, 24 )
                                                .addComponent( 点券 ) ) )
                                .addGap( 245, 245, 245 )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( 抽卡, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( 购买, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addGap( 28, 28, 28 )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE )
                                .addGroup( UpLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, UpLayout.createSequentialGroup()
                                                .addComponent( 返回, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 156, 156, 156 ) )
                                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, UpLayout.createSequentialGroup()
                                                .addComponent( 充值, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                .addGap( 166, 166, 166 ) ) ) )
                                 );

        BackGroundLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/backGround/b1.png" ) ) ); // NOI18N
        BackGroundLabel.setOpaque( true );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout( BackGround );
        BackGround.setLayout( BackGroundLayout );
        BackGroundLayout.setHorizontalGroup(
                BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 1165, Short.MAX_VALUE )
                        .addGroup( BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( BackGroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent( BackGroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addContainerGap() ) )
                                           );
        BackGroundLayout.setVerticalGroup(
                BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 784, Short.MAX_VALUE )
                        .addGroup( BackGroundLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addGroup( BackGroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent( BackGroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addContainerGap() ) )
                                         );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 1165, Short.MAX_VALUE )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                 );
        layout.setVerticalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGap( 0, 784, Short.MAX_VALUE )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                        .addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                               );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 返回ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_返回ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Main_UI().setVisible( true );
    }//GEN-LAST:event_返回ActionPerformed

    private void 购买ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_购买ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Gacha_Single().setVisible( true );
    }//GEN-LAST:event_购买ActionPerformed

    private void 抽卡ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_抽卡ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Gacha_5().setVisible( true );
    }//GEN-LAST:event_抽卡ActionPerformed

    private void 充值ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_充值ActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
        new Recharge().setVisible( true );
    }//GEN-LAST:event_充值ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ){
                if( "Nimbus".equals( info.getName() ) ){
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }catch( ClassNotFoundException ex ){
            java.util.logging.Logger.getLogger( Store_Gacha.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( InstantiationException ex ){
            java.util.logging.Logger.getLogger( Store_Gacha.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( IllegalAccessException ex ){
            java.util.logging.Logger.getLogger( Store_Gacha.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }catch( javax.swing.UnsupportedLookAndFeelException ex ){
            java.util.logging.Logger.getLogger( Store_Gacha.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Store_Gacha().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JPanel Up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton 充值;
    private javax.swing.JLabel 呢称;
    private javax.swing.JLabel 头像;
    private javax.swing.JButton 抽卡;
    private javax.swing.JLabel 点券;
    private javax.swing.JLabel 等级;
    private javax.swing.JButton 购买;
    private javax.swing.JButton 返回;
    // End of variables declaration//GEN-END:variables
}
